# Generated by Django 3.0.10 on 2024-05-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('region', models.CharField(choices=[('NEAR EAST', 'NEAR EAST'), ('ASIA (EX. NEAR EAST)', 'ASIA (EX. NEAR EAST)'), ('C.W. OF IND. STATES', 'C.W. OF IND. STATES'), ('OCEANIA', 'OCEANIA'), ('NORTHERN AMERICA', 'NORTHERN AMERICA'), ('EASTERN EUROPE', 'EASTERN EUROPE'), ('WESTERN EUROPE', 'WESTERN EUROPE'), ('NORTHERN AFRICA', 'NORTHERN AFRICA'), ('LATIN AMER. & CARIB', 'LATIN AMER. & CARIB'), ('SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA'), ('BALTICS', 'BALTICS')], max_length=500)),
                ('population', models.IntegerField()),
                ('population_density', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gdp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gdp_per_capita', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
