# Generated by Django 3.0.10 on 2024-05-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_viewer', '0002_auto_20240516_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(choices=[('BALTICS', 'BALTICS'), ('C.W. OF IND. STATES', 'C.W. OF IND. STATES'), ('OCEANIA', 'OCEANIA'), ('NORTHERN AMERICA', 'NORTHERN AMERICA'), ('LATIN AMER. & CARIB', 'LATIN AMER. & CARIB'), ('ASIA (EX. NEAR EAST)', 'ASIA (EX. NEAR EAST)'), ('NEAR EAST', 'NEAR EAST'), ('EASTERN EUROPE', 'EASTERN EUROPE'), ('NORTHERN AFRICA', 'NORTHERN AFRICA'), ('WESTERN EUROPE', 'WESTERN EUROPE'), ('SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA')], max_length=500),
        ),
    ]
