# Generated by Django 5.0.1 on 2024-05-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_viewer', '0011_alter_country_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='clcks_left',
            new_name='no_click',
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(choices=[('WESTERN EUROPE', 'WESTERN EUROPE'), ('SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA'), ('BALTICS', 'BALTICS'), ('ASIA (EX. NEAR EAST)', 'ASIA (EX. NEAR EAST)'), ('OCEANIA', 'OCEANIA'), ('NORTHERN AFRICA', 'NORTHERN AFRICA'), ('EASTERN EUROPE', 'EASTERN EUROPE'), ('C.W. OF IND. STATES', 'C.W. OF IND. STATES'), ('NEAR EAST', 'NEAR EAST'), ('NORTHERN AMERICA', 'NORTHERN AMERICA'), ('LATIN AMER. & CARIB', 'LATIN AMER. & CARIB')], max_length=500),
        ),
    ]
