# Generated by Django 3.0.10 on 2024-05-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='gdp',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='country',
            name='gdp_per_capita',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='country',
            name='population_density',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(choices=[('OCEANIA', 'OCEANIA'), ('BALTICS', 'BALTICS'), ('LATIN AMER. & CARIB', 'LATIN AMER. & CARIB'), ('SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA'), ('ASIA (EX. NEAR EAST)', 'ASIA (EX. NEAR EAST)'), ('NORTHERN AMERICA', 'NORTHERN AMERICA'), ('C.W. OF IND. STATES', 'C.W. OF IND. STATES'), ('NEAR EAST', 'NEAR EAST'), ('EASTERN EUROPE', 'EASTERN EUROPE'), ('NORTHERN AFRICA', 'NORTHERN AFRICA'), ('WESTERN EUROPE', 'WESTERN EUROPE')], max_length=500),
        ),
    ]
