# Generated by Django 5.0.1 on 2024-05-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_viewer', '0003_auto_20240516_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(choices=[('ASIA (EX. NEAR EAST)', 'ASIA (EX. NEAR EAST)'), ('EASTERN EUROPE', 'EASTERN EUROPE'), ('BALTICS', 'BALTICS'), ('SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA'), ('OCEANIA', 'OCEANIA'), ('C.W. OF IND. STATES', 'C.W. OF IND. STATES'), ('NORTHERN AFRICA', 'NORTHERN AFRICA'), ('LATIN AMER. & CARIB', 'LATIN AMER. & CARIB'), ('WESTERN EUROPE', 'WESTERN EUROPE'), ('NORTHERN AMERICA', 'NORTHERN AMERICA'), ('NEAR EAST', 'NEAR EAST')], max_length=500),
        ),
    ]
