# Generated by Django 5.0.1 on 2024-05-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_viewer', '0006_alter_country_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(choices=[('ASIA (EX. NEAR EAST)', 'ASIA (EX. NEAR EAST)'), ('WESTERN EUROPE', 'WESTERN EUROPE'), ('BALTICS', 'BALTICS'), ('C.W. OF IND. STATES', 'C.W. OF IND. STATES'), ('EASTERN EUROPE', 'EASTERN EUROPE'), ('NORTHERN AMERICA', 'NORTHERN AMERICA'), ('NORTHERN AFRICA', 'NORTHERN AFRICA'), ('OCEANIA', 'OCEANIA'), ('LATIN AMER. & CARIB', 'LATIN AMER. & CARIB'), ('NEAR EAST', 'NEAR EAST'), ('SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA')], max_length=500),
        ),
    ]
