# Generated by Django 5.0.1 on 2024-05-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_viewer', '0007_alter_country_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(choices=[('NORTHERN AFRICA', 'NORTHERN AFRICA'), ('ASIA (EX. NEAR EAST)', 'ASIA (EX. NEAR EAST)'), ('WESTERN EUROPE', 'WESTERN EUROPE'), ('BALTICS', 'BALTICS'), ('OCEANIA', 'OCEANIA'), ('NORTHERN AMERICA', 'NORTHERN AMERICA'), ('SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA'), ('C.W. OF IND. STATES', 'C.W. OF IND. STATES'), ('EASTERN EUROPE', 'EASTERN EUROPE'), ('NEAR EAST', 'NEAR EAST'), ('LATIN AMER. & CARIB', 'LATIN AMER. & CARIB')], max_length=500),
        ),
    ]
