# Generated by Django 5.0.1 on 2024-05-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_viewer', '0010_alter_country_region_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(choices=[('NORTHERN AMERICA', 'NORTHERN AMERICA'), ('LATIN AMER. & CARIB', 'LATIN AMER. & CARIB'), ('OCEANIA', 'OCEANIA'), ('EASTERN EUROPE', 'EASTERN EUROPE'), ('BALTICS', 'BALTICS'), ('NEAR EAST', 'NEAR EAST'), ('C.W. OF IND. STATES', 'C.W. OF IND. STATES'), ('WESTERN EUROPE', 'WESTERN EUROPE'), ('SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA'), ('ASIA (EX. NEAR EAST)', 'ASIA (EX. NEAR EAST)'), ('NORTHERN AFRICA', 'NORTHERN AFRICA')], max_length=500),
        ),
    ]
