# Generated by Django 5.0.1 on 2024-05-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_viewer', '0012_rename_clcks_left_profile_no_click_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(choices=[('OCEANIA', 'OCEANIA'), ('EASTERN EUROPE', 'EASTERN EUROPE'), ('SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA'), ('WESTERN EUROPE', 'WESTERN EUROPE'), ('LATIN AMER. & CARIB', 'LATIN AMER. & CARIB'), ('BALTICS', 'BALTICS'), ('ASIA (EX. NEAR EAST)', 'ASIA (EX. NEAR EAST)'), ('NEAR EAST', 'NEAR EAST'), ('NORTHERN AFRICA', 'NORTHERN AFRICA'), ('NORTHERN AMERICA', 'NORTHERN AMERICA'), ('C.W. OF IND. STATES', 'C.W. OF IND. STATES')], max_length=500),
        ),
    ]
