# Generated by Django 4.2.13 on 2024-05-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('current_price', models.DecimalField(decimal_places=5, max_digits=30)),
                ('open_price', models.DecimalField(decimal_places=5, max_digits=30)),
                ('min_price', models.DecimalField(decimal_places=5, max_digits=30)),
                ('max_price', models.DecimalField(decimal_places=5, max_digits=30)),
            ],
        ),
    ]
