# Generated by Django 4.2.13 on 2024-05-29 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_viewer', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=30)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock_viewer.stock')),
            ],
        ),
    ]
